spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
management.endpoint.health.show-details=never
management.health.mail.enabled=false