spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/libratrack}
spring.datasource.username=${DB_USER:libratrack}
spring.datasource.password=${DB_PASS:changeme}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
app.jwt.secret=${JWT_SECRET:default-dev-secret-32-chars-min!!!}
app.max-loans-student=${MAX_LOANS_STUDENT:3}
app.max-loans-faculty=${MAX_LOANS_FACULTY:5}
management.endpoints.web.exposure.include=health,info
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
spring.data.web.pageable.max-page-size=100