CREATE TABLE users (id BIGSERIAL PRIMARY KEY,email VARCHAR(255) NOT NULL UNIQUE,password_hash VARCHAR(255) NOT NULL,role VARCHAR(20) NOT NULL CHECK (role IN ('ADMIN','LIBRARIAN','STUDENT','FACULTY')),full_name VARCHAR(200) NOT NULL,student_id VARCHAR(50) UNIQUE,active BOOLEAN NOT NULL DEFAULT true,created_at TIMESTAMP NOT NULL DEFAULT now());
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_role ON users(role);
