-- V8: Seed sample books for development/testing

INSERT INTO books (title, author, isbn, publisher, published_year, category, description, total_copies, created_at)
VALUES
  ('Clean Code',
   'Robert C. Martin',
   '978-0132350884',
   'Prentice Hall',
   2008,
   'ENGINEERING',
   'A handbook of agile software craftsmanship covering naming, functions, comments, formatting, and error handling.',
   3,
   now()),

  ('The Pragmatic Programmer',
   'David Thomas, Andrew Hunt',
   '978-0135957059',
   'Addison-Wesley',
   2019,
   'ENGINEERING',
   'Practical advice on becoming a better programmer.',
   2,
   now()),

  ('Design Patterns',
   'Gang of Four',
   '978-0201633610',
   'Addison-Wesley',
   1994,
   'ENGINEERING',
   'Elements of reusable object-oriented software. The classic reference for design patterns.',
   2,
   now()),

  ('Introduction to Algorithms',
   'Cormen, Leiserson, Rivest, Stein',
   '978-0262046305',
   'MIT Press',
   2022,
   'SCIENCE',
   'Comprehensive introduction to algorithms - the standard university textbook.',
   4,
   now()),

  ('Sapiens: A Brief History of Humankind',
   'Yuval Noah Harari',
   '978-0062316097',
   'Harper',
   2015,
   'HUMANITIES',
   'A survey of the history of humankind from the evolution of archaic human species to the twenty-first century.',
   2,
   now()),

  ('The Great Gatsby',
   'F. Scott Fitzgerald',
   '978-0743273565',
   'Scribner',
   1925,
   'HUMANITIES',
   'A portrait of the Jazz Age and the dark side of the American Dream.',
   3,
   now())
ON CONFLICT (isbn) DO NOTHING;